name: Catalog Service CI/CD

on:
  push:
    branches:
      - main
  pull_request:

permissions:
    id-token: write
    contents: read

env:
    IMAGE_NAME: catalog-service

jobs:
    build-test-scan-deploy:
        runs-on: ubuntu-latest


        steps: 
  # ----------------------------
  # Checkout
  # ----------------------------
            - name: Checkout
              uses: actions/checkout@v4

  # ----------------------------
  # Gitleaks
  # ----------------------------
            - name: Run Gitleaks
              uses: gitleaks/gitleaks-action@v2
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}
  # ----------------------------
  # Setup Go
  # ----------------------------
           
            # ----------------------------
            # Commit GitOps Change
            # ----------------------------
            - name: Verify remote URL
              run: |
                 cd gitops-platform
                 git remote -v

            - name: Test PAT
              run: |
                curl -i \
                  -H "Authorization: Bearer ${{ secrets.GITOPS_TOKEN }}" \
                  https://api.github.com/repos/Ingress-Q/gitops-platform

          
           
            - name: Check token owner
              run: |
                curl -s \
                  -H "Authorization: Bearer ${{ secrets.GITOPS_TOKEN }}" \
                   https://api.github.com/user
           
          
            - name: Check repo permissions
              run: |
                curl -i \
                    -H "Authorization: Bearer ${{ secrets.GITOPS_TOKEN }}" \
                    "https://api.github.com/repos/Ingress-Q/gitops-platform/collaborators/Piyushhh3/permission"
          
          
          
            - name: Check branch protection
              run: |
                curl -s 
                -H "Authorization: Bearer ${{ secrets.GITOPS_TOKEN }}" \
                "https://api.github.com/repos/Ingress-Q/gitops-platform/branches/main/protection"


          
          
          
          
          
          
          
          
          
          
            - name: Commit and Push GitOps Change
              run: |
                cd gitops-platform

                git config user.email "gitops-bot@company.com"
                git config user.name "gitops-bot"

                git add .

                git commit -m "chore(catalog): update image tag to ${GITHUB_SHA}" || true
                git remote set-url origin \
                     https://x-access-token:${{ secrets.GITOPS_TOKEN }}@github.com/Ingress-Q/gitops-platform.git

                git push origin main
          
            